### ISSUE TITLE
could you clarify a sentence from the paper?

### ISSUE THREAD

**Issue by ghost** [hehaodele/ProbGAN#1]
Page 5 of the paper, just over Theory section.

> Hence we propose to maintain a subset of discriminators by subsampling the whole sequence of discriminators.

Isn't this conceptually similar to image buffer, where we store random set of prior images from dataset to train discriminator? if not how does it differs?

**Comment by hehaodele** [comment]
Instead of image buffer, we maintain a discriminator buffer that stores a subset of discriminators that from the previous training steps. 
Thus main difference is the buffer stores discriminator weights rather than images.
